### ISSUE TITLE
'methods' of undefined

### ISSUE THREAD

**Issue by MuhammadSaim** [nickgraffis/tailwind-toast#1]
```javascript
// tailwindcss toasts
const {toast, snackbar} = require('tailwind-toast');


toast().default("Success", "This is my message").as('pill').show();
```

having an issue while running the package <kbd>Uncaught TypeError: Can not read property 'methods' of undefined</kbd>

Note: I'm using webpack encore and tailwind 2.1.1

![image](https://user-images.githubusercontent.com/19898499/114355126-88540f80-9b88-11eb-9e32-01e774fd4043.png)

![image](https://user-images.githubusercontent.com/19898499/114355843-61e2a400-9b89-11eb-8137-5faf54fbc50d.png)

**Comment by nickgraffis** [comment]
This seems t have been an issue with require.main. 
[https://github.com/nickgraffis/tailwind-toast/commit/42338813c488f82806ac95e6263294272e8ef40d](https://github.com/nickgraffis/tailwind-toast/commit/42338813c488f82806ac95e6263294272e8ef40d
)

I made a small change in this commit.

Try npm update.

Thanks!

**Comment by MuhammadSaim** [comment]
Great mate.! Thanks for your precious time
