### ISSUE TITLE
Toast Bottom position

### ISSUE THREAD

**Issue by MuhammadSaim** [nickgraffis/tailwind-toast#2]
I want to use toasts in the bottom start but the bottom is not working always displayed on the top. also, method chaining is not working I set the delay for 500000 but its works on the default value when I use with then it's working fine but positionY is not working.

```javascript
const {toast, snackbar} = require('tailwind-toast');

toast()
    .warning('Hey!', 'There was a minor error!')
    .for(500000)
    .from('bottom', 'start').show() //display with all parameters
```

![image](https://user-images.githubusercontent.com/19898499/114518634-fff16f80-9c58-11eb-970a-7a98cc595063.png)

**Note** You left the <kbd>console</kbd> in your <kbd>Toast.js</kbd> at line number [L96](https://github.com/nickgraffis/tailwind-toast/blob/42338813c488f82806ac95e6263294272e8ef40d/classes/Toast.js#L96)

**Comment by nickgraffis** [comment]
Fixed in this [PR](https://github.com/nickgraffis/tailwind-toast/pull/3)
