### ISSUE TITLE
Support for tailwind light and dark mode

### ISSUE THREAD

**Issue by mikerhyssmith** [nickgraffis/tailwind-toast#7]
Im not sure if its possible and Ive not been able to work it out. I was hoping to make toasts different colours depending on light and dark mode without having to programatically find out which mode tailwind is currently in?

Would also be happy to have a go at adding it if you are interested 😄

**Comment by nickgraffis** [comment]
This brings up something important. Currently we are accepting color and tone parameters, but honestly. We should be accepting the entire color. 

Ie: .with({ color: 'bg-blue-300' }). 

This will be better for helping tailwinds purge. AND if we do it this way, there is nothing stopping you from doing:

.with({ color: 'dark: bg-blue-800 bg-blue-300' }).

Feel free to open a pr.

**Comment by mikerhyssmith** [comment]
@nickgraffis Sorry its taken me so long to get back to you ! I'm going to take a look at this, this week 😄

**Comment by ShubhankarKG** [comment]
Is this up for grabs yet @nickgraffis ? I can maybe file in a draft PR.

**Comment by mikerhyssmith** [comment]
Ahh sorry I checked this out, started working on it then life happened 😆  Im not sure ill get back to it quicker than you will so feel free !

**Comment by nickgraffis** [comment]
Go for it @ShubhankarKG . 

And no worries @mikerhyssmith .

Thanks everyone!
